In [ ]:
# Analytics
#1. Numpy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#2. Pandas
#3. Matplotlib
#4. Seaborn

In [12]:
import numpy as np

In [3]:
di = [10 , 20 , 30]
ti = [5,10,15]

sp = di/ti
print(sp)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
print(di+ti)

[10, 20, 30, 5, 10, 15]


In [10]:
d = numpy.array(di)
t = numpy.array(ti)
sp = d/t
sp

array([2., 2., 2.])

In [11]:
# Numpy stands for numerical python. It is a pyton foundational that is used for performing maathematical operation , \
# linear algebric function and many more. Numpy consists 2 things array & matrix

In [ ]:
# ndim
# shape
# size
# dtype

In [ ]:
# List - list are my data type
# we can't perform the mathematical operations in list
# Time ccomplexity of list is very high

# array - array is a method that is imported by numpy
# we can perform mathematical operations in array
# Time complexity of array is low that's why we store data in the form of array

In [51]:
a1 = np.array([1,2,3,4])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[1 2 3 4]
1
(4,)
4


In [38]:
a = np.array([[1,2,3,4,5]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3 4 5]]
2
(1, 5)


In [45]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [46]:
a3=np.array([[1,2,3,4,5],[5,6,7,8,9],[1,1,1,1,1],[0,0,0,0,0]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [0 0 0 0 0]]
2
(4, 5)
20


In [52]:
x=np.array([[1],[3],[4]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[1]
 [3]
 [4]]
2
(3, 1)
3
int64


In [48]:
y=np.array([[2,3],[4,5],[7,8],[1,1]])
# print(y.ndim)
print(y.shape)
print(y.size)

(4, 2)
8


In [ ]:
d=np.array([[[[1,2,3.5],[5,6,7],[7,8,9]]]])
print(d,type(d))
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)

[[[[1.  2.  3.5]
   [5.  6.  7. ]
   [7.  8.  9. ]]]] <class 'numpy.ndarray'>
4
(1, 1, 3, 3)
9
float64


In [ ]:
e=np.array([[[[1,2,3],[5,6,7],[7,8,9],[7,8,9],[1,1,1]]]])
print(e,type(e))
#print(e.ndim)
#print(e.shape)
#print(e.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]
   [7 8 9]
   [1 1 1]]]] <class 'numpy.ndarray'>
4
(1, 1, 5, 3)
15


# Indexing & Slicing

In [77]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[ 1  2  3  4  5  6 -7  8  9]]]


In [79]:
# print(a[0])
# print(a[0][0])
# print(a[0][0][0])
# print(a[0][0][1])
# print(a[0][0][-3])
# print(a[-1][-1][-3])
# print(a[0][-1][3])

4


In [92]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print(c)
# print(c.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [90]:
# print(c[0])
# print(c[0][0])
# print(c[3][2])
# print(c[-1][-2])
# print(c[-1][1])
# print(c[-4][-2])
# print(c[2][-2])


In [93]:
import numpy as np
f=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(f)
# print(f.ndim)
# print(f.size)
# print(f.shape)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [97]:
# print(f[0][0][-2])
# print(f[-1][0][-4][0])
# print(f[0][0][1])
print(f[0][-1][3][2])

18


In [98]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [117]:
# print(f[0][0][rows,columns])
# print(f[0][0][1:3,1:4])
# print(f[0][0][-4:-2])
# print(f[0][0][-4:-3,-4:-3])
# print(f[-1][-1][-1:,-1:])
# print(f[-1][-1][1:,-1:])
# print(f[-1][-1][-1:,:-1])
# print(f[-1][0][-2:,2:100])
# print(f[0][0][1:4,-4:-1])
# print(f[0][-1][-3:-2,0:4])

# SHAPE Manipulation

In [134]:
x = np.array([[1,2,3,4],[5,6,7,8],[1,1,1,1]])
print(x)
print(x.shape)
print(x.size)

[[1 2 3 4]
 [5 6 7 8]
 [1 1 1 1]]
(3, 4)
12


In [127]:
print(x.reshape(2,6))

[[1 2 3 4 5 6]
 [7 8 1 1 1 1]]


In [128]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [130]:
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [132]:
np.transpose(c)

array([[ 1,  4,  7, 11],
       [ 2,  5,  8, 12],
       [ 3,  6,  9, 13]])

In [133]:
c.T

array([[ 1,  4,  7, 11],
       [ 2,  5,  8, 12],
       [ 3,  6,  9, 13]])

# Broadcasting

In [135]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [139]:
print(a*b)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [140]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [142]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [143]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
np.sum(a)

np.int64(45)

In [148]:
print(np.sum(a,axis=0)) # here axis = 0 means rows
print(np.sum(a,axis=1))# here axis = 1 means cols

[12 15 18]
[ 6 15 24]


In [152]:
np.fromfunction(lambda i,j : i+j,(2,7),dtype=int)

array([[0, 1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6, 7]])

In [153]:
np.fromfunction(lambda i,j : i>j,(2,2))

array([[False, False],
       [ True, False]])

In [171]:
a = np.array([[[1,2,3],[4,5,6]]])
b = np.array([[1,1,1],[2,2,2]])

print(a,type(a))

[[[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'>


In [167]:
print(a*b)

[[[ 1  2  3]
  [ 8 10 12]]]


In [168]:
x = np.matrix([[1,2,3],[4,5,6]])
y = np.matrix([[1,1,1],[2,2,2]])

print(x,type(x))

[[1 2 3]
 [4 5 6]] <class 'numpy.matrix'>


In [173]:
y = y.T
y

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [174]:
print(x*y)

[[ 6 12]
 [15 30]]


# Array creation

In [176]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [177]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [181]:
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [191]:
a = np.ones((5,5),dtype=int)
a[1:4 ,1:4 ] = b
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [190]:
b = np.zeros((3,3),dtype=int)
b[1][1]=9
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [197]:
L=[]
for i in range(1,26):
    a = int(input(f'enter the no{i} to add in array '))
    L.append(a)

enter the no1 to add in array  1
enter the no2 to add in array  1
enter the no3 to add in array  1
enter the no4 to add in array  1
enter the no5 to add in array  1
enter the no6 to add in array  1
enter the no7 to add in array  0
enter the no8 to add in array  0
enter the no9 to add in array  0
enter the no10 to add in array  1
enter the no11 to add in array  1
enter the no12 to add in array  0
enter the no13 to add in array  9
enter the no14 to add in array  0
enter the no15 to add in array  1
enter the no16 to add in array  1
enter the no17 to add in array  0
enter the no18 to add in array  0
enter the no19 to add in array  0
enter the no20 to add in array  1
enter the no21 to add in array  1
enter the no22 to add in array  1
enter the no23 to add in array  1
enter the no24 to add in array  1
enter the no25 to add in array  1


In [201]:
np.array(L,ndmin=2).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# Conditions in array

In [214]:
M = np.array([55,70,29,80,38,1,32])
pas = 50
M[M>50]

array([55, 70, 80])

In [194]:
z = np.array([[1,2,3]],ndmin=10)
print(z)
print(z.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [195]:
print(z.ravel())

[1 2 3]


In [218]:
np.arange(1,10,3)

array([1, 4, 7])

In [217]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [237]:
np.random.randint(1,7)

1

In [257]:
L=['a','b','c']

print(np.random.choice(L))

c


In [ ]:
shape
indexing & slicing
broadcasting
sum of row and cols
filtering

In [ ]:
# Pandas